name: Storybook Preview

on:
  pull_request:
    branches: [main]

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build UI package (ensure dist for story imports if needed)
        run: pnpm build --filter @internal/ui

      - name: Build Storybook
        run: pnpm --filter @internal/ui build-storybook

      - name: Upload Storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-ui
          path: packages/ui/storybook-static
          if-no-files-found: error
